### PR TITLE
Correct docs regarding miovision streetcar classification

### PR DESCRIPTION
**Pull request by Nate-Wessel**
## What this pull request accomplishes:

- reclassifies streetcars as "buses"
- adds link to Miovision's documentation of this
- applies more standard formatting to that markdown table for readability

## What, in particular, needs to reviewed:

- That streetcars are in fact classified as buses

### CODE REVIEW

**Comment by radumas** [comment]
That document doesn't say anything about streetcars being classified as buses

**Comment by radumas** [comment]
From a 2019 email

>The reason you might see two 'Bus' Classes is this: 'Motorized Vehicles' happens to be what we label Streetcars. We have found in Toronto that it seems like the only thing our Motorized Vehicle class is catching are Streetcars. Per an earlier conversation we had, I think it was your preference that we label streetcars as buses, so we have introduced this mapping,
Motorized Vehicle -> Bus
>Bus is also a separate class type.
>So we generate two items in the API if in the same bin, at least one bus and one street car make the same movement.

**Comment by Nate-Wessel** [comment]
It's near the bottom under "additional information"

> Trams and streetcars are grouped with the Bus class. If your study requires a separate Trams volume, select Trams as a [custom classification](https://help.miovision.com/s/article/Custom-Classifications-in-Traffic-Data-Online?language=en_US).

**Comment by Nate-Wessel** [comment]
> From a 2019 email
> 
> > The reason you might see two 'Bus' Classes is this: 'Motorized Vehicles' happens to be what we label Streetcars. We have found in Toronto that it seems like the only thing our Motorized Vehicle class is catching are Streetcars. Per an earlier conversation we had, I think it was your preference that we label streetcars as buses, so we have introduced this mapping,
> > Motorized Vehicle -> Bus
> > Bus is also a separate class type.
> > So we generate two items in the API if in the same bin, at least one bus and one street car make the same movement.

Is this saying that streetcars would have been be double-counted? Once as a bus, and again as a MotorizedVehicle?

My _suspicion_ at this point is that this email may have been correct in 2019, but something changed sometime later on and now streetcars are simply classified as buses. It's the only way that current volumes at e.g. King and Spadina make sense.

**Comment by Nate-Wessel** [comment]
Copying a message from Jesse posted in Slack:
> Just a quick followup, miovision did confirm that streetcars did in fact change classification with an algorithm change at some point, they were going to investigate further to figure out when exactly etc  (they used to be classified as motorized vehicles, and now seem to be classified as buses) ...

**Comment by Nate-Wessel** [comment]
This seems like a decent case for being handled in part through the Miovision QC tables, proposed in https://github.com/CityofToronto/bdit_data-sources/pull/589. This would be a note applying to this `classification_uid` for all intersections, separately both for the pre- and post- periods. I think there may also be some variation in implementation time between intersections, though my best guess at the moment is that this rolled out around 2019-08-01 for most. 

Should of course also be noted in the documentation here.

**Comment by Nate-Wessel** [comment]
I added a note to the docs to really spell this out. IMO, we can open a separate issue to properly pin down the exact date of the change.

**Review by radumas — APPROVED** [review]

**Pull request merged**
