### PR TITLE
716 add a data volume check to pull wys task

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:
- Adds a row count check to the daily pull_wys DAG
- Adds a distinct sign count check to the daily pull_wys DAG (DISTINCT api_id) 
- This uses the same sql/airflow template as merged ~~#702~~ **Updated:** #730 . 

## Issue(s) this solves:
- #716 

## What, in particular, needs to reviewed:
- The params used (60 day lookback, 0.7 threshold)

## What needs to be done by a sysadmin after this PR is merged
- It may be easier to wait to merge #659 first, as we are already running significant modifications to the DAG off that branch.

### CODE REVIEW

**Review by radumas — APPROVED** [review]
This looks great! Really solid emphasis on generalizable building blocks we can apply to other pipelines.

We could generalize the api_id count lookback to receive something like `sensor_id_col` as a param and then that could be potentially applied to allll (many?) of the sensor based data streams.

**Comment by gabrielwol** [comment]
Thanks! Note that `SQLCheckOperatorWithReturnValue` was first added by Islam for VFH. 
Good idea, I'll add `sensor_id_col` to params.

**Comment by gabrielwol** [comment]
Noting the potential for issue #730 to manifest on this DAG as well as they share similar SQL.

**Comment by gabrielwol** [comment]
Fixed the failures on this task from Saturday/Sunday by adding template search path. Also adjusted the sqls to match #732: query aggregate table instead of raw. `[Tested](https://10.162.65.124/airflow/dags/pull_wys/grid?base_date=2023-10-28T23%3A59%3A59.999Z&dag_run_id=scheduled__2023-10-27T19%3A00%3A00%2B00%3A00&task_id=data_checks.check_row_count&tab=logs)` ✅ .

**Pull request merged**
