### PR TITLE
Miovision Pipeline Upgrade to Support Bike Approaches

### PR DESCRIPTION
**Pull request by cczhu**
## What this pull request accomplishes:

- Includes bicycle ATRs as class 10 road users, with corresponding movement 7 and 8 as approach and departing volumes.
- Revises the API pull function to unify crosswalk and non-crosswalk code, provide support for class 10 road users, and make some of the mapping between API response codes and the codes we use in `miovision_api.volumes` more Pythonic.
- Includes development notebook `06 - Bike Approach Sandbox.ipynb` to document testing and validation of the new pipeline (comparing six days of data from May 20, 2021 - May 25, 2021 inclusive), and ancillary files to eg. generate a test environment for pulling and aggregating under the `czhu` schema.

## Issue(s) this solves:

- #403

## What, in particular, needs to reviewed:

- Vet revisions to `intersection_tmc.py`.
- Review of pipeline design as described in #403.
- Check that SQL scripts conform to pipeline design. In particular double check whether any new code will break any of the gap finding and record keeping functions, which have not been changed.
- Inspect `czhu.miovision_volumes`, `czhu.miovision_volumes_15min_tmc` and `czhu.miovision_volumes_15min` for anomalies.
- Simultaneously @cczhu to continue working with Brent to determine why bike approach volumes are much lower than TMCs for many intersections.

To productionize:
- Update `intersection_movements` and `movement_map`.
- Delete extraneous and legacy tables from `miovision_api`, or at least add `_archiveDONOTUSE` to their names.
- Delete test pipeline in `czhu`
- Rename `miovision_api.volumes_15min_tmc` to `miovision_api.volumes_15min_mvt`, and create a `miovision_api.volumes_15min_tmc` view that only contains turning movement counts.
- Rename the following 😬 
  - `miovision_api.volumes_15min_tmc`
  - `volume_15min_tmc_uid`
  - `volumes_volumes_15min_tmc_uid_fkey`
  - `volumes_15min_tmc_pkey`
  - `volumes_15min_tmc_intersection_uid_datetime_bin_classificat_key`
  - All the indexes of `miovision_api.volumes_15min_tmc`
  - `volumes_tmc_atr_xover`
  - All indexes to `volumes_tmc_atr_xover`
  - `volume_15min_tmc_uid`
  - `atr_tmc_uid_volume_15min_mvt_uid_fkey`
  - `atr_tmc_uid_volume_15min_uid_fkey`
  - `aggregate_15_min` references (though those should change automatically??)
  - Any archived versions of `intersection` or `intersection_movements`?

### CODE REVIEW

**Comment by cczhu** [comment]
On top of the tasks above, we should consider deleting:

`czhu`:

Functions:
- aggregate_15_min
- aggregate_15_min_tmc
- miov_find_gaps

Tables:
- intersection_movements
- miov_15minapi_hragg
- miov_15mincsv_hragg
- miov_15minoldapi_hragg
- miov_volumes_2020
- miovapi_15min_dec2020
- miovision_api_dailycounts
- miovision_csv_dailycounts
- miovision_oldapi_dailycounts
- miovision_volumes
- miovision_volumes_15min
- miovision_volumes_15min_mvt
- miovision_volumes_15min_tmc_t4est
- miovision_volumes_mvt_atr_xover
- movement_map

Views:
- volumes_15min_tmc

`miovision_api`:

Functions:
- aggregate_15min_tmc_old
- find_gaps_test

Tables:
- intersections_20200805
- intersections_20201122
- intersection_movements_20200805
- intersection_movements_20201116
- intersection_movements_20210603 (though maybe we should keep a copy somewhere)
- volumes_2019_old

All of `miovision_new`

This includes cleanup for #405, #408, and #358

**Comment by cczhu** [comment]
Fixed relevant CodeFactor issues. The remaining issues, in files produced only for comparative testing between old and new versions of `intersection_tmc.py`, shouldn't be addressed.

**Comment by radumas** [comment]
I'm reasonably certain this code gets us 95% of the way to a mass rename.

```sql
select 'ALTER ' || case cls.relkind
         when 'r' then 'TABLE'
         when 'i' then 'INDEX'
         when 'S' then 'SEQUENCE'
         when 'v' then 'VIEW'
         when 'c' then 'TYPE'
         when 'm' then 'MATERIALIZED VIEW'
         else cls.relkind::text END
		 || ' ' ||
		 nsp.nspname 
		 || '.' ||
         cls.relname 
         || ' RENAME TO ' ||
		 replace(cls.relname, 'tmc', 'mvt')
         ||';'
       
from pg_class cls
  join pg_roles rol on rol.oid = cls.relowner
  join pg_namespace nsp on nsp.oid = cls.relnamespace
where nsp.nspname = 'miovision_api'
	AND cls.relname  LIKE '%15min_tmc%'
```

With some text processing the resulting command is the below. There may need to be some reordering of commands.

```sql
ALTER INDEX miovision_api.volumes_2021_volume_15min_tmc_uid_idx RENAME TO 'volumes_2021_volume_15min_mvt_uid_idx';
ALTER SEQUENCE miovision_api.volumes_15min_tmc_volume_15min_tmc_uid_seq RENAME TO 'volumes_15min_mvt_volume_15min_mvt_uid_seq';
ALTER INDEX miovision_api.volumes_15min_tmc_datetime_bin_idx RENAME TO 'volumes_15min_mvt_datetime_bin_idx';
ALTER INDEX miovision_api.volumes_tmc_atr_xover_volume_15min_tmc_uid_idx RENAME TO 'volumes_mvt_atr_xover_volume_15min_mvt_uid_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_pkey RENAME TO 'volumes_15min_mvt_pkey';
ALTER INDEX miovision_api.volumes_15min_tmc_classification_uid_idx RENAME TO 'volumes_15min_mvt_classification_uid_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_intersection_uid_idx RENAME TO 'volumes_15min_mvt_intersection_uid_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_leg_movement_uid_idx RENAME TO 'volumes_15min_mvt_leg_movement_uid_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_volume_15min_tmc_uid_idx RENAME TO 'volumes_15min_mvt_volume_15min_mvt_uid_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_processed_idx RENAME TO 'volumes_15min_mvt_processed_idx';
ALTER INDEX miovision_api.volumes_15min_tmc_intersection_uid_datetime_bin_classificat_key RENAME TO 'volumes_15min_mvt_intersection_uid_datetime_bin_classificat_key';
ALTER TABLE miovision_api.volumes_15min_tmc RENAME TO 'volumes_15min_mvt';
ALTER INDEX miovision_api.volumes_2020_volume_15min_tmc_uid_idx RENAME TO 'volumes_2020_volume_15min_mvt_uid_idx';
ALTER INDEX miovision_api.volumes_2018_volume_15min_tmc_uid_idx RENAME TO 'volumes_2018_volume_15min_mvt_uid_idx';
ALTER SEQUENCE miovision_api.volumes_15min_tmc_volume_15min_tmc_uid_test_seq RENAME TO 'volumes_15min_mvt_volume_15min_mvt_uid_test_seq';
ALTER INDEX miovision_api.volumes_volume_15min_tmc_uid_idx RENAME TO 'volumes_volume_15min_mvt_uid_idx';
ALTER INDEX miovision_api.volumes_2019_volume_15min_tmc_uid_idx RENAME TO 'volumes_2019_volume_15min_mvt_uid_idx';
```

**Review by radumas — CHANGES_REQUESTED** [review]
This looks pretty great!

Thanks for formatting the sql nicer.

Shouldn't there be changes to the main README for miovision?

**Comment by cczhu** [comment]
Thanks for the review!

There indeed should be changes to `README.md`, but I was reluctant to implement them because of the time involved 😳

**Comment by radumas** [comment]
To rename the columns

```sql
select 'ALTER TABLE ' || 
		 nsp.nspname 
		 || '.' ||
		 cls.relname
		 || ' RENAME COLUMN ' ||
		 a.attname 
		 || ' TO ' ||
		 replace(a.attname ,'tmc','mvt')
		 ||';'
from pg_class as cls
	  join pg_namespace nsp on nsp.oid = cls.relnamespace
    inner join pg_attribute as a on a.attrelid = cls.oid
where a.attname LIKE 'volume_15min_tmc%' and cls.relkind = 'r' AND nsp.nspname = 'miovision_api'
```

Note that child columns will be automatically updated to the parent columns and can't be altered directly.

For constraints

```sql
select 'ALTER TABLE ' || 
		 nsp.nspname 
		 || '.' ||
		 cls.relname
		 || ' RENAME CONSTRAINT ' ||
		 conname
		 || ' TO ' ||
		 replace(conname,'tmc','mvt')
		 ||';'
from pg_constraint c
  join pg_namespace nsp on nsp.oid = c.connamespace
  join pg_class as cls ON conrelid= cls.oid
where conname LIKE '%volume_15min_tmc%'
and nsp.nspname = 'miovision_api'
```

**Review by radumas — APPROVED** [review]

**Comment by cczhu** [comment]
Testing productionization by deleting 2021-07-11 data and re-pulling, and checking if we now have bike approach volumes (class 10 movement 7):

```sql
DELETE FROM miovision_api.volumes
WHERE datetime_bin BETWEEN '2021-07-11 00:00:00' AND '2021-07-11 23:59:00';

DELETE FROM miovision_api.volumes_15min_mvt
WHERE datetime_bin BETWEEN '2021-07-10 23:00:00' AND '2021-07-11 22:45:00';

DELETE FROM miovision_api.volumes_15min
WHERE datetime_bin BETWEEN '2021-07-10 23:00:00' AND '2021-07-11 22:45:00';

DELETE FROM miovision_api.report_dates
WHERE dt = '2021-07-11';

DELETE FROM miovision_api.api_log
WHERE start_date = '2021-07-11';

DELETE FROM miovision_api.unacceptable_gaps
WHERE gap_start BETWEEN '2021-07-10 23:00:00' AND '2021-07-11 22:45:00';

**Pull request merged**
