### PR TITLE
Make `text_to_centreline` more case-insensitive

### PR DESCRIPTION
**Pull request by Nate-Wessel**
## What this pull request accomplishes:

- removes case-sensitivity from words like "of" and "point"

## Issue(s) this solves:

- This briefly tripped me up on a recent data request where the input came in all-caps, and was transformed with `InitCap`. I wouldn't expect "A Point 100 Metres South..." to be handled differently from "a point 100 metres south..."

## What, in particular, needs to reviewed:

- minor change to one function

## What needs to be done by a sysadmin after this PR is merged

replace `gis.text_to_centreline` with the updated function

### CODE REVIEW

**Comment by Nate-Wessel** [comment]
I'm happy to fluff this, though this small change will be easier to review if I keep the changes simple.

**Review by radumas — APPROVED** [review]
Cimpl Change Chanks.

**Comment by Nate-Wessel** [comment]
@radumas or @chmnata can this get implemented and merged?

**Comment by radumas** [comment]
Implement and merged

**Pull request merged**
