### PR TITLE
Update DAGs in data script to be as cool as airflow 2

### LINKED ISSUE #524: Update DAG to be airflow 2.0 compatible
Mainly:
 Using `airflow.operators.postgres_operator.PostgresOperator` should be replaced by `airflow.providers.postgres.operators.postgres.PostgresOperator`.  and 
Using `airflow.contrib.operators.slack_webhook_operator.SlackWebhookOperator` should be replaced by `airflow.providers.slack.operators.slack_webhook.SlackWebhookOperator`

### PR DESCRIPTION
**Pull request by chmnata**
## What this pull request accomplishes:

- Update DAGs used in data script (not dev_script) to be compatible with airflow 2, mainly changing postgreshook, postgres opeartor and slackwebhookoperator

## Issue(s) this solves:

- Closes #524 

## What, in particular, needs to reviewed:

- no typos in the new ones?

### CODE REVIEW

**Comment by chmnata** [comment]
sorry, not ready yet. something about slack operators

**Comment by chmnata** [comment]
I thought the slackoperators needs to be 
`airflow.providers.slack.operators.slack_webhook.SlackWebhookOperator`
instead of 
`airflow.contrib.operators.slack_webhook_operator `
According to the below output when I run `airflow upgrade check`
```
 1.  Using `airflow.contrib.operators.slack_webhook_operator.SlackWebhookOperator` should be replaced by `airflow.providers.slack.operators.slack_webhook.SlackWebhookOperator`. Affected file: /etc/airflow/dags/generate_congestion_agg.py
```
But if I change the slackoperator to `airflow.providers.slack.operators.slack_webhook.SlackWebhookOperator` as stated by the output
it yells at me 
image

The below stackoverflow answer stated that `The bridge version still uses pre 2.0 syntax. The changes to import path is only valid in 2.0`, so I guess it would be fine once we upgraded to 2.0 🤔 
https://stackoverflow.com/questions/67233220/upgrading-to-airflow-2-no-module-named-airflow-hooks-base

**Comment by tahaislam** [comment]
The airflow 1.x syntax `from airflow.contrib.operators.slack_webhook_operator import SlackWebhookOperator` works in Airflow 2.1.4. It'd just show a warning.
I replaced the above with `from airflow.providers.slack.operators.slack_webhook import SlackWebhookOperator` to remove the warning

**Comment by chmnata** [comment]
I can import `from airflow.providers.postgres.hooks.postgres.PostgresHook import PostgresHook` in python3 but the dag is broken. I think airflow is still running python2
image
image

**Comment by chmnata** [comment]
Made a mistake, added an extra postgreshook after postgres. in 
 `from airflow.providers.postgres.hooks.postgres.PostgresHook import PostgresHook`

**Review by tahaislam — APPROVED** [review]

**Pull request merged**
