### PR TITLE
774 useful views depending on artery px are a trap

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:

- Fix trap view joining arterydata and PX. 

## Issue(s) this solves:

- #774, #1064

## What, in particular, needs to reviewed:

- 

## What needs to be done by a sysadmin after this PR is merged

- [x] To keep dependencies we should `CREATE VIEW traffic.artery_locations_px_DO_NOT_USE AS ...` and then `ALTER VIEW traffic.artery_locations_px_DO_NOT_USE RENAME TO traffic.artery_locations_px`. 
- [x] Also `DROP traffic.artery_traffic_signals_DO_NOT_USE`. 
- [x] Comment on two data requests that the view has changed.

### CODE REVIEW

**Comment by radumas** [comment]
> To keep dependencies we should CREATE VIEW traffic.artery_locations_px_DO_NOT_USE AS ... and then ALTER VIEW traffic.artery_locations_px_DO_NOT_USE RENAME TO traffic.artery_locations_px.

Unfortunately I think postgres actually stores VIEW dependencies as references to the OIDs. So the relationship will persist whatever the name (Except for objects referenced in functions, I think).

We'll have to use the dependency saver instead.

**Comment by radumas** [comment]
Code looks good. I agree with the fluff though 🐑  please fix the SQL

**Comment by gabrielwol** [comment]
> > To keep dependencies we should CREATE VIEW traffic.artery_locations_px_DO_NOT_USE AS ... and then ALTER VIEW traffic.artery_locations_px_DO_NOT_USE RENAME TO traffic.artery_locations_px.
> 
> Unfortunately I think postgres actually stores VIEW dependencies as references to the OIDs. So the relationship will persist whatever the name (Except for objects referenced in functions, I think).
> 
> We'll have to use the dependency saver instead.

I was able to use `CREATE OR REPLACE VIEW ...` and `ALTER VIEW ... RENAME TO` and have the dependencies remain linked!

**Comment by gabrielwol** [comment]
Implemented and ready to merge with your approval @radumas

**Comment by radumas** [comment]
> > > To keep dependencies we should CREATE VIEW traffic.artery_locations_px_DO_NOT_USE AS ... and then ALTER VIEW traffic.artery_locations_px_DO_NOT_USE RENAME TO traffic.artery_locations_px.
> > 
> > 
> > Unfortunately I think postgres actually stores VIEW dependencies as references to the OIDs. So the relationship will persist whatever the name (Except for objects referenced in functions, I think).
> > We'll have to use the dependency saver instead.
> 
> I was able to use `CREATE OR REPLACE VIEW ...` and `ALTER VIEW ... RENAME TO` and have the dependencies remain linked!

Right. I didn't follow the bit about replacing the bad view. That works in line with my understanding of how things work.

**Review by radumas — APPROVED** [review]
Looks great! People are going to have such efficient lives now.

**Pull request merged**
