### PR TITLE
Here docs update

### PR DESCRIPTION
**Pull request by Nate-Wessel**
## What this pull request accomplishes:
- updates Here docs to reflect current schema

## What, in particular, needs to reviewed:
- `here/README.md`

### CODE REVIEW

**Comment by chmnata** [comment]
looks like this is branched off from sarah's doc_here branch? We also have this #488 HERE doc PR outstanding, wondering if you also modified the doc according to Raph's comment on that PR.

**Comment by Nate-Wessel** [comment]
I hadn't looked at those - just updated the table to reflect the current schema, and my best understanding of the various fields. 

This is branched off of master. 

I'd be happy to take a look at those other branches too and see if we can incorporate their changes as well, after this one. We'll probably have some conflicting edits to deal with at some point...

**Review by chmnata — APPROVED** [review]
much clearer, thanks for adding the description for samplecounts and confidence!

**Comment by Nate-Wessel** [comment]
@chmnata thanks for the quick review!

**Pull request merged**
