### PR TITLE
775 fix slack webhook warning in data sources

### LINKED ISSUE #775: Fix Slack Webhook warning in data-sources
```WARNING - /data/airflow/airflow_venv/lib/python3.10/site-packages/airflow/providers/slack/operators/slack_webhook.py:153 AirflowProviderDeprecationWarning: Provide `webhook_token` as hook argument deprecated by security reason and will be removed in a future releases. Please specify it in `Slack Webhook` connection.```
Use changes implemented in https://github.com/Toronto-Big-Data-Innovation-Team/vfh_data_mgmt/pull/167.

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:
- Fixes the slack webhook warning in `task_fail_slack_alert` of data-sources repo. Same fix in `eoy_create_tables.py` 
- Removes unused SlackWebhookOperator imports and others in the same files as per pylance warnings. 
- [replace DAG param schedule_interval with schedule](https://github.com/CityofToronto/bdit_data-sources/pull/776/commits/0abfdb748294f108a465253bdffe51bd855f1e26)
- [replace DAG param task_concurrency with max_active_tis_per_dag](https://github.com/CityofToronto/bdit_data-sources/pull/776/commits/7b3470c17c6739ec2e730631259f2cf27e3e3185)

## Issue(s) this solves:
- Closes #775

### CODE REVIEW

**Comment by tahaislam** [comment]
good fixes. There're some other depreciation warnings. Do you want to fix them in this PR? Or should I create a separate issue for this?

image

**Review by tahaislam — APPROVED** [review]

**Comment by gabrielwol** [comment]
> good fixes. There're some other depreciation warnings. Do you want to fix them in this PR? Or should I create a separate issue for this?
> 
> image

Sure I'll fix those here too!

**Comment by gabrielwol** [comment]
@tahaislam ready for re-review

**Review by tahaislam — APPROVED** [review]
Thanks for fixing these warnings

**Pull request merged**
