### PR TITLE
973 ecocounter investigate discrepency between bigdata and online dashboard tools

### PR DESCRIPTION
**Pull request by gabrielwol**
## What this pull request accomplishes:
- captures 401 and other bad api status_codes (encountered during testing, but doesn't appear to be the issue)
- changes schedule to 10am to capture data from some late arriving sensors (this was the issue)
- add logging for when 0 volumes are pulled for a site

See runs from Master (Log 1) / 973 (Log 2) here: https://trans-bdit.intra.prod-toronto.ca/airflow/dags/ecocounter_pull/grid?dag_run_id=scheduled__2024-06-12T07%3A00%3A00%2B00%3A00&task_id=data_checks.check_volume&tab=logs
- 14K rows pulled at 3AM ❌ 
- 21K rows pulled at 9:40AM ✔️ 

## Issue(s) this solves:

- #973 

## What, in particular, needs to reviewed:

-

### CODE REVIEW

**Comment by chmnata** [comment]
Are we sure 10am captures all sites? If one site has a delay does our checking dag alerts for it?

**Comment by gabrielwol** [comment]
There's at least one case documented where a sensor dumped 5 days of data after not reporting for 5 days: #984 
So I think 10am is good for now and then another process to capture late arriving data is necessary.

**Comment by chmnata** [comment]
Got it :meow_salute:

**Review by chmnata — APPROVED** [review]
Approved :pedro:

**Pull request merged**
