### PR TITLE
Mohan Branched

### PR DESCRIPTION
**Pull request by webgisgeek**
Mohan branched it for review and update

## What this pull request accomplishes:
- Raphael needs to confirm the changes/proposed changes in the detector table comments field to clear up the inconsistencies.

## Issue(s) this solves:

- A clean and up-to-date BT detector inventory table

## What, in particular, needs to reviewed:
- Please review the comments field status after filtering the Status field for 'For Review'

### CODE REVIEW

**Comment by webgisgeek** [comment]
@radumas Please check the excel sheet. I will finalize it after your reveiw. 

[BT_detectors_Inventory_for_review.xlsx](https://github.com/CityofToronto/bdit_data-sources/files/5189453/BT_detectors_Inventory_for_review.xlsx)

**Comment by radumas** [comment]
@chmnata @KatiRG if you could review the route generation instructions that would be great

**Review by radumas — CHANGES_REQUESTED** [review]
Bit hard to review the dags in one branch that depend on the sql in the other...

Haven't finished reviewing the sql but have some initial comments for you to work on.

**Comment by chmnata** [comment]
Closing, outdated and superseded by #391

**Pull request closed without merging**
